name: kishore
on: workflow_dispatch

jobs:
  manualjob:
    runs-on: ubuntu-latest
    steps:
      - name: firstjob
        run: echo "helloworld"
      - name: second job
        run: echo "I am learning github actions"

  secondjob:
    runs-on: ubuntu-latest
    steps:
      - name: third job
        run: echo "thisrjob"
