name: learn
on: push

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      new: ${{ steps.version.outputs.image_version }}
    steps:
      - name: checkout the code
        id: version
        run: ls -lrt >> $GITHUB_OUTPUT

  job2:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: step
        run: echo "version = ${{ needs.checkout.outputs.new }}"
